CREATE EXTENSION IF NOT EXISTS pg_stat_statements;
CREATE EXTENSION IF NOT EXISTS btree_gist;
CREATE EXTENSION IF NOT EXISTS powa;

-- 建立登入帳號
CREATE ROLE powa LOGIN PASSWORD 'powa';

-- 重要：必須 superuser
ALTER ROLE powa WITH SUPERUSER;

GRANT ALL PRIVILEGES ON DATABASE powa TO powa;