$$START_TIME = '2026-04-01';
$$END_TIME = '2026-05-01';
$$LOG_TABLE_NAME = 'machine_status_logs_2026_04';
$$TARGET_TABLE_NAME = 'machine_status_logs';
$$SCHEMA_NAME = 'oltp';

CREATE TABLE $$SCHEMA_NAME.$$LOG_TABLE_NAME
PARTITION OF $$SCHEMA_NAME.$$TARGET_TABLE_NAME
FOR VALUES FROM ($$START_TIME) TO ($$END_TIME);